AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An Amazon DynamoDB trigger that logs the updates made to a table.
Resources:
  dynamodbstreamsreplicator:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: dynamodb-streams-replicator
      Handler: dynamo_to_dynamo_replicator_simple.lambda_handler
      Runtime: python2.7
      CodeUri: ../../package/lambda-dynamo-replicator.zip
      Description: DynamoDB to DynamoDB replicator function
      MemorySize: 128
      Timeout: 300
      Role: 'arn:aws:iam::000000000000:role/lambda-dynamo-replication-execution-role'
      Events:
        DynamoDB1:
          Type: DynamoDB
          Properties:
            Stream:
              'Fn::GetAtt':
                - Table1
                - StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
  Table1:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: user-visits-sam
      SSESpecification: 
        SSEEnabled: True
      AttributeDefinitions:
        - AttributeName: EventId
          AttributeType: S
      KeySchema:
        - AttributeName: EventId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  Table2:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: user-visits-sam-replicated
      SSESpecification: 
        SSEEnabled: True
      AttributeDefinitions:
        - AttributeName: EventId
          AttributeType: S
      KeySchema:
        - AttributeName: EventId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1